In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier,ExtraTreesRegressor , RandomForestRegressor
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
import pickle
from sklearn.neural_network import MLPClassifier

C:\Users\master\Anaconda3\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
C:\Users\master\Anaconda3\lib\site-packages\dask\dataframe\utils.py:13: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
C:\Users\master\Anaconda3\lib\site-packages\distributed\config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)


In [2]:
df = pd.read_csv('submission files/test.csv')
df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [3]:
df.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          326
Embarked         0
dtype: int64

In [4]:
df['Has_Cabin'] = df["Cabin"].apply(lambda x: 0 if type(x) == float else 1)
df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Has_Cabin  
0  34.5      0      0   330911   7.8292   NaN        Q          0  
1  47.0      1      0   363272   7.0000   NaN        S          0  
2  62.0      0      0   240276   9.6875   NaN        Q          0  
3  27.0      0      0   315154   8.6625   NaN        S          0  
4  22.0      1      1  3101298  12.2875   NaN        S          0

In [5]:
df['Has_Cabin'].value_counts()

0    326
1     92
Name: Has_Cabin, dtype: int64

In [6]:
df.drop(columns= ['PassengerId', 'Name', 'Cabin', 'Ticket', 'Embarked'], inplace=True)
df.head()

Pclass     Sex   Age  SibSp  Parch     Fare  Has_Cabin
0       3    male  34.5      0      0   7.8292          0
1       3  female  47.0      1      0   7.0000          0
2       2    male  62.0      0      0   9.6875          0
3       3    male  27.0      0      0   8.6625          0
4       3  female  22.0      1      1  12.2875          0

In [7]:
df['Fare'] = df['Fare'].fillna(df['Fare'].mean())

In [8]:
X = df.iloc[:,:].values
X

array([[3, 'male', 34.5, ..., 0, 7.8292, 0],
       [3, 'female', 47.0, ..., 0, 7.0, 0],
       [2, 'male', 62.0, ..., 0, 9.6875, 0],
       ...,
       [3, 'male', 38.5, ..., 0, 7.25, 0],
       [3, 'male', 34.0, ..., 0, 8.05, 0],
       [3, 'male', 5.0, ..., 1, 22.3583, 0]], dtype=object)

In [9]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 3 ... 0 7.8292 0]
 [1.0 0.0 3 ... 0 7.0 0]
 [0.0 1.0 2 ... 0 9.6875 0]
 ...
 [0.0 1.0 3 ... 0 7.25 0]
 [0.0 1.0 3 ... 0 8.05 0]
 [0.0 1.0 3 ... 1 22.3583 0]]


In [10]:
sc = StandardScaler()
X[:, 2:] = sc.fit_transform(X[:, 2:])

In [11]:
filename = 'LogisticRegression_model808.sav'
loaded_model = pickle.load(open(filename, 'rb'))
pred = loaded_model.predict(X)
sub = pd.read_csv('submission files/gender_submission.csv', delimiter=',')
sub.drop(columns=['Survived'], inplace=True)
sub['Survived'] = pred
sub
sub.to_csv('submission files/readylrnewapp3081.csv', index=False)

In [12]:
filename = 'MLPClassifier_model837.sav'
loaded_model = pickle.load(open(filename, 'rb'))
pred = loaded_model.predict(X)
sub = pd.read_csv('submission files/gender_submission.csv', delimiter=',')
sub.drop(columns=['Survived'], inplace=True)
sub['Survived'] = pred
sub
sub.to_csv('submission files/readymlp837.csv', index=False)