In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
import pickle

In [12]:
df = pd.read_csv('test.csv')
df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [13]:
df ['Age'] = df['Age'].fillna(df['Age'].mean())
df['Fare'] = df['Fare'].fillna(df['Fare'].mean())
df.isnull().sum()
df['Age'] = df['Age'].astype('int32')

In [14]:
df.drop(columns=['PassengerId', 'Name', 'Cabin', 'Embarked', 'Ticket','Fare'], inplace=True)

In [15]:
df

Pclass     Sex  Age  SibSp  Parch
0         3    male   34      0      0
1         3  female   47      1      0
2         2    male   62      0      0
3         3    male   27      0      0
4         3  female   22      1      1
..      ...     ...  ...    ...    ...
413       3    male   30      0      0
414       1  female   39      0      0
415       3    male   38      0      0
416       3    male   30      0      0
417       3    male   30      1      1

[418 rows x 5 columns]

In [16]:
X = df.iloc[:,:].values
X

array([[3, 'male', 34, 0, 0],
       [3, 'female', 47, 1, 0],
       [2, 'male', 62, 0, 0],
       ...,
       [3, 'male', 38, 0, 0],
       [3, 'male', 30, 0, 0],
       [3, 'male', 30, 1, 1]], dtype=object)

In [17]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 3 34 0 0]
 [1.0 0.0 3 47 1 0]
 [0.0 1.0 2 62 0 0]
 ...
 [0.0 1.0 3 38 0 0]
 [0.0 1.0 3 30 0 0]
 [0.0 1.0 3 30 1 1]]


In [18]:
sc = StandardScaler()
X[:, 2:] = sc.fit_transform(X[:, 2:])
X

C:\Users\master\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\master\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.0, 1.0, 0.8734819050636105, 0.30133910185069557,
        -0.4994700165357186, -0.4002477016385638],
       [1.0, 0.0, 0.8734819050636105, 1.3299048552782577,
        0.6169923733676523, -0.4002477016385638],
       [0.0, 1.0, -0.3158191904301653, 2.5167114938485216,
        -0.4994700165357186, -0.4002477016385638],
       ...,
       [0.0, 1.0, 0.8734819050636105, 0.6178208721360993,
        -0.4994700165357186, -0.4002477016385638],
       [0.0, 1.0, 0.8734819050636105, -0.01514266843470818,
        -0.4994700165357186, -0.4002477016385638],
       [0.0, 1.0, 0.8734819050636105, -0.01514266843470818,
        0.6169923733676523, 0.6198958305865561]], dtype=object)

# LOGISTIC REGRESSION PREDICTION 76%

In [19]:
filename = 'LogisticRegression_model.sav'
loaded_modelreg = pickle.load(open(filename, 'rb'))
X

array([[0.0, 1.0, 0.8734819050636105, 0.30133910185069557,
        -0.4994700165357186, -0.4002477016385638],
       [1.0, 0.0, 0.8734819050636105, 1.3299048552782577,
        0.6169923733676523, -0.4002477016385638],
       [0.0, 1.0, -0.3158191904301653, 2.5167114938485216,
        -0.4994700165357186, -0.4002477016385638],
       ...,
       [0.0, 1.0, 0.8734819050636105, 0.6178208721360993,
        -0.4994700165357186, -0.4002477016385638],
       [0.0, 1.0, 0.8734819050636105, -0.01514266843470818,
        -0.4994700165357186, -0.4002477016385638],
       [0.0, 1.0, 0.8734819050636105, -0.01514266843470818,
        0.6169923733676523, 0.6198958305865561]], dtype=object)

In [20]:
y_predreg = loaded_modelreg.predict(X)
y_predreg

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [21]:
sub = pd.read_csv('gender_submission.csv', delimiter=',')
sub

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [22]:
sub.drop(columns=['Survived'], inplace=True)


In [24]:
sub['Survived'] = y_predreg

In [25]:
sub
sub.to_csv('ready.csv', index=False)

In [55]:
filename = 'XGBClassifier_model.sav'
loaded_model = pickle.load(open(filename, 'rb'))
X

array([[0.0, 1.0, 0.8734819050636105, ..., -0.49947001653571715,
        -0.40024770163856266, -0.4984070560437162],
       [1.0, 0.0, 0.8734819050636105, ..., 0.6169923733676506,
        -0.40024770163856266, -0.513274287571346],
       [0.0, 1.0, -0.3158191904301653, ..., -0.49947001653571715,
        -0.40024770163856266, -0.4650884642108722],
       ...,
       [0.0, 1.0, 0.8734819050636105, ..., -0.49947001653571715,
        -0.40024770163856266, -0.5087918853982787],
       [0.0, 1.0, 0.8734819050636105, ..., -0.49947001653571715,
        -0.40024770163856266, -0.49444819844446314],
       [0.0, 1.0, 0.8734819050636105, ..., 0.6169923733676506,
        0.6198958305865546, -0.23790597839286678]], dtype=object)

In [42]:
sub.drop(columns=['Survived'], inplace=True)

KeyError: "['Survived'] not found in axis"

In [59]:
y_predxgr = loaded_model.predict(X)
y_predxgr

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [60]:
y_pred = loaded_modelreg.predict(X)
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,