In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
import pickle
import numpy as np
from sklearn.metrics import accuracy_score
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, BatchNormalization
from keras.optimizers import SGD
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

C:\Users\master\Anaconda3\lib\site-packages\h5py\__init__.py:72: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Using TensorFlow backend.


In [2]:
df = pd.read_csv('../submission files/train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
print(df.info())
df['Age'] = df['Age'].fillna(df['Age'].mean())
print(df.info())
labels = ['child','adult', 'old']
df['age_group'] = pd.cut(df['Age'], bins=3, labels=labels)
df['age_group']= df['age_group'].fillna('adult')
df.isnull().sum()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          853 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Sur

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
age_group        0
dtype: int64

In [4]:
labels = ['cheap', 'normal', 'expensive']
df['Fare_group'] = pd.cut(df['Fare'], bins=3, labels=labels)
df['Fare_group']= df['Fare_group'].fillna('cheap')
print(df.isnull().sum())
df

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
age_group        0
Fare_group       0
dtype: int64


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   7.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked age_group Fare_group  
0        0         A/5 21171   7.2500   NaN        S     child      cheap  
1        0          PC 17599  71.2833   C85        C     adult      cheap  
2        0  STON/O2. 3101282   7.9250   NaN        S     child      cheap  
3        0            113803  53.1000  C123        S     adult      cheap  
4        0            373450   8.0500   NaN        S     adult      cheap  
..     ...               ...      ...   ...      ...       ...        ...  
886      0            211536  13.0000   NaN        S     adult      cheap  
887      0            112053  30.0000   B42        S     child      cheap  
888      2        W./C. 6607  23.4500   NaN        S     child      cheap  
889      0            111369  30.0000  C148        C     child      cheap  
890      0            370376   7.7500   NaN        Q     adult      cheap  

[891 rows x 14 columns]

In [5]:
df.drop(columns= ['PassengerId', 'Name', 'Cabin', 'Embarked', 'Ticket','Age', 'Fare'], inplace=True)
df

Survived  Pclass     Sex  SibSp  Parch age_group Fare_group
0           0       3    male      1      0     child      cheap
1           1       1  female      1      0     adult      cheap
2           1       3  female      0      0     child      cheap
3           1       1  female      1      0     adult      cheap
4           0       3    male      0      0     adult      cheap
..        ...     ...     ...    ...    ...       ...        ...
886         0       2    male      0      0     adult      cheap
887         1       1  female      0      0     child      cheap
888         0       3  female      1      2     child      cheap
889         1       1    male      0      0     child      cheap
890         0       3    male      0      0     adult      cheap

[891 rows x 7 columns]

In [6]:
y = df.iloc[:, 0].values
X = df.iloc[:,1:].values
X

array([[3, 'male', 1, 0, 'child', 'cheap'],
       [1, 'female', 1, 0, 'adult', 'cheap'],
       [3, 'female', 0, 0, 'child', 'cheap'],
       ...,
       [3, 'female', 1, 2, 'child', 'cheap'],
       [1, 'male', 0, 0, 'child', 'cheap'],
       [3, 'male', 0, 0, 'adult', 'cheap']], dtype=object)

In [7]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,4,-1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 ... 3 1 0]
 [1.0 0.0 1.0 ... 1 1 0]
 [1.0 0.0 0.0 ... 3 0 0]
 ...
 [1.0 0.0 0.0 ... 3 1 2]
 [0.0 1.0 0.0 ... 1 0 0]
 [0.0 1.0 1.0 ... 3 0 0]]


In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 11)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[0.0 1.0 0.0 ... 3 2 0]
 [0.0 1.0 1.0 ... 1 0 0]
 [0.0 1.0 1.0 ... 3 0 0]
 ...
 [0.0 1.0 0.0 ... 3 0 0]
 [0.0 1.0 0.0 ... 3 0 0]
 [0.0 1.0 0.0 ... 3 0 0]]
[[1.0 0.0 1.0 ... 3 1 0]
 [0.0 1.0 1.0 ... 3 0 0]
 [0.0 1.0 0.0 ... 3 0 0]
 ...
 [0.0 1.0 0.0 ... 3 0 0]
 [0.0 1.0 1.0 ... 1 0 0]
 [0.0 1.0 0.0 ... 1 1 0]]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0
 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0
 0 0 0 1 1 0 0 0 0 1 1 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0 1 1 0
 1 0 1 0 1 0 1 1 0 0 1 1 0 1 0 1 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0
 0 0 1 1 1 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 1 0 1 1 0 0 1 0 1 1 0
 1 1 1 1 1 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 1 0 0 1 1 1 0 1 1 1 1 0 0 0 0 0
 1 1 0 1 1 1 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0
 1 0 1 0 0 1 0 1 1 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1
 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0
 0 1 0 0 1 1 

In [9]:
sc = StandardScaler()
X_train[:, 2:] = sc.fit_transform(X_train[:, 2:])
X_test[:, 2:] = sc.transform(X_test[:, 2:])
print(X_train)
print(X_test)

[[0.0 1.0 -1.0227301753122666 ... 0.8249189043748203 1.291688566808702
  -0.4811217256593604]
 [0.0 1.0 0.977775002771068 ... -1.557808316375167 -0.4684688677708115
  -0.4811217256593604]
 [0.0 1.0 0.977775002771068 ... 0.8249189043748203 -0.4684688677708115
  -0.4811217256593604]
 ...
 [0.0 1.0 -1.0227301753122666 ... 0.8249189043748203 -0.4684688677708115
  -0.4811217256593604]
 [0.0 1.0 -1.0227301753122666 ... 0.8249189043748203 -0.4684688677708115
  -0.4811217256593604]
 [0.0 1.0 -1.0227301753122666 ... 0.8249189043748203 -0.4684688677708115
  -0.4811217256593604]]
[[1.0 0.0 0.977775002771068 ... 0.8249189043748203 0.41160984951894514
  -0.4811217256593604]
 [0.0 1.0 0.977775002771068 ... 0.8249189043748203 -0.4684688677708115
  -0.4811217256593604]
 [0.0 1.0 -1.0227301753122666 ... 0.8249189043748203 -0.4684688677708115
  -0.4811217256593604]
 ...
 [0.0 1.0 -1.0227301753122666 ... 0.8249189043748203 -0.4684688677708115
  -0.4811217256593604]
 [0.0 1.0 0.977775002771068 ... -1.5578

In [10]:
model = Sequential()
model.add(Dense(11, init='uniform', activation='relu', input_dim=11))
model.add(BatchNormalization())
model.add(Dense(64, init = 'uniform', activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(32, init = 'uniform', activation='relu'))
model.add(Dropout(0.4))
model.add(BatchNormalization())
model.add(Dense(64, init = 'uniform', activation='relu'))
model.add(Dense(32, init = 'uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))
model.compile(loss='binary_crossentropy',
 optimizer='adam',
 metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 11)                132       
_________________________________________________________________
batch_normalization_1 (Batch (None, 11)                44        
_________________________________________________________________
dense_2 (Dense)              (None, 64)                768       
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 32)                2080      
_________________________________________________________________
dropout_2 (Dropout)          (None, 32)                0         
_________________________________________________________________
batch_normalization_2 (Batch (None, 32)               

C:\Users\master\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(11, activation="relu", input_dim=11, kernel_initializer="uniform")`
  
C:\Users\master\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(64, activation="relu", kernel_initializer="uniform")`
  after removing the cwd from sys.path.
C:\Users\master\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(32, activation="relu", kernel_initializer="uniform")`
  
C:\Users\master\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(64, activation="relu", kernel_initializer="uniform")`
  if __name__ == '__main__':
C:\Users\master\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(32, activation="relu", k

In [19]:
model.fit(X_train, y_train,validation_split=0.3,batch_size=32, epochs =100)

Train on 498 samples, validate on 214 samples
Epoch 1/100
498/498 [==============================] - 0s 54us/step - loss: 0.3701 - accuracy: 0.8434 - val_loss: 0.5086 - val_accuracy: 0.7477
Epoch 2/100
498/498 [==============================] - 0s 51us/step - loss: 0.4047 - accuracy: 0.8273 - val_loss: 0.4995 - val_accuracy: 0.7430
Epoch 3/100
498/498 [==============================] - 0s 50us/step - loss: 0.3855 - accuracy: 0.8213 - val_loss: 0.5243 - val_accuracy: 0.7336
Epoch 4/100
498/498 [==============================] - 0s 48us/step - loss: 0.3840 - accuracy: 0.8373 - val_loss: 0.5245 - val_accuracy: 0.7430
Epoch 5/100
498/498 [==============================] - 0s 48us/step - loss: 0.4147 - accuracy: 0.8012 - val_loss: 0.5102 - val_accuracy: 0.7617
Epoch 6/100
498/498 [==============================] - 0s 49us/step - loss: 0.3664 - accuracy: 0.8333 - val_loss: 0.4989 - val_accuracy: 0.7570
Epoch 7/100
498/498 [==============================] - 0s 50us/step - loss: 0.4001 - accur

Epoch 57/100
498/498 [==============================] - 0s 50us/step - loss: 0.3904 - accuracy: 0.8293 - val_loss: 0.4946 - val_accuracy: 0.7523
Epoch 58/100
498/498 [==============================] - 0s 50us/step - loss: 0.3651 - accuracy: 0.8394 - val_loss: 0.4886 - val_accuracy: 0.7523
Epoch 59/100
498/498 [==============================] - 0s 48us/step - loss: 0.3657 - accuracy: 0.8313 - val_loss: 0.4940 - val_accuracy: 0.7477
Epoch 60/100
498/498 [==============================] - 0s 48us/step - loss: 0.4065 - accuracy: 0.8173 - val_loss: 0.4873 - val_accuracy: 0.7477
Epoch 61/100
498/498 [==============================] - 0s 48us/step - loss: 0.3925 - accuracy: 0.8233 - val_loss: 0.4925 - val_accuracy: 0.7570
Epoch 62/100
498/498 [==============================] - 0s 50us/step - loss: 0.3696 - accuracy: 0.8373 - val_loss: 0.4997 - val_accuracy: 0.7523
Epoch 63/100
498/498 [==============================] - 0s 106us/step - loss: 0.3794 - accuracy: 0.8173 - val_loss: 0.4985 - val_a

In [20]:
predictions= model.predict(X_test).tolist()
print(predictions)


[[0.6412330269813538], [0.12378493696451187], [0.1175304651260376], [0.1169368103146553], [0.10992245376110077], [0.1169368103146553], [0.1175304651260376], [0.5530200600624084], [0.13458040356636047], [0.9174248576164246], [0.1169368103146553], [0.2130408138036728], [0.1175304651260376], [0.1175304651260376], [0.4678383767604828], [0.1175304651260376], [0.06464191526174545], [0.04995541274547577], [0.4810585081577301], [0.6064865589141846], [0.12353295087814331], [0.1053657978773117], [0.1175304651260376], [0.1175304651260376], [0.047275640070438385], [0.04995541274547577], [0.12353295087814331], [0.10756105184555054], [0.04995541274547577], [0.4810585081577301], [0.9820230603218079], [0.9222332835197449], [0.06464191526174545], [0.5711316466331482], [0.4810585081577301], [0.04995541274547577], [0.1525365710258484], [0.5990972518920898], [0.020709313452243805], [0.12378493696451187], [0.04995541274547577], [0.26533159613609314], [0.9222332835197449], [0.8866462707519531], [0.553020060

In [21]:
se = pd.Series(predictions)
df['check'] = se
df['check'] = df['check'].str.get(0)

In [22]:
finalpred = []
for val in df.check:
    if val >=0.5:
        finalpred.append(1)
    else:
        finalpred.append(0)

df['Prediction'] = finalpred

In [23]:
df

Survived  Pclass     Sex  SibSp  Parch age_group Fare_group     check  \
0           0       3    male      1      0     child      cheap  0.641233   
1           1       1  female      1      0     adult      cheap  0.123785   
2           1       3  female      0      0     child      cheap  0.117530   
3           1       1  female      1      0     adult      cheap  0.116937   
4           0       3    male      0      0     adult      cheap  0.109922   
..        ...     ...     ...    ...    ...       ...        ...       ...   
886         0       2    male      0      0     adult      cheap       NaN   
887         1       1  female      0      0     child      cheap       NaN   
888         0       3  female      1      2     child      cheap       NaN   
889         1       1    male      0      0     child      cheap       NaN   
890         0       3    male      0      0     adult      cheap       NaN   

     Prediction  
0             1  
1             0  
2             0  
3             0  
4             0  
..          ...  
886           0  
887           0  
888           0  
889           0  
890           0  

[891 rows x 9 columns]

In [24]:
filename='titanic8293.sav'
pickle.dump(model, open(filename, 'wb'))